import Head from 'next/head'
import styles from '../styles/Home.module.css'
import initializeApollo from '../lib/apollo'
import { useEffect, useState } from 'react'
import { gql, useLazyQuery, useMuitation, useSubscription } from '@apollo/client'
import { Button, Container, Grid, Item, Stack, Typography } from '@mui/material'
import MakeAppt from '../components/MakeAppt'
import ApptTable from '../components/ApptTable'
import PatientCombo from '../components/PatientCombo'
import DoctorCombo from '../components/DoctorCombo'
import DateCombo from '../components/DateCombo'
import UploadFile from '../components/UploadFile'


const Home = ({ patientData, doctorData }) => {
  const [ selectedDoctorName, setSelectedDoctorName ] = useState("")
  const [ selectedPatientName, setSelectedPatientName ] = useState("")
  const [ selectedPatientQuery, setSelectedPatientQuery ] = useState("")
  const [ selectedDoctorQuery, setSelectedDoctorQuery ] = useState("")
  const [ selectedDateTime, setSelectedDateTime ] = useState(new Date())

  // const [ apptData, setApptData] = useState([])
  // const [ apptLoading, setApptLoading ] = useState()
  // const [ apptError, setApptError ] = useState

  const queryOptions = {
        variables: {
          "params": {}
        }
      }

  const GET_APPTS = gql`
    query getAppointments($params: appointment_bool_exp!) {
      appointment(where: $params) {
        appointment_id
        appt_datetime
        consulting_doctor
        doctorByConsultingDoctor {
          doctor_id
          doctor_name
        }
        visiting_patient
        patientByVisitingPatient {
          patient_name
          patient_age
          patient_gender
        }
      }
    }`


    const [ loadAppointments, { called, loading: apptLoading , error: apptError, data: apptData}] = useLazyQuery(GET_APPTS, queryOptions)

    useEffect(()=> {
      loadAppointments(queryOptions)
    }, [])


    const handleVarChange = () => {
      
      if (selectedDoctorQuery){
        queryOptions.variables.params.consulting_doctor = selectedDoctorQuery
      }
      if (selectedPatientQuery) {
        queryOptions.variables.params.visiting_patient = selectedPatientQuery
      }
      if (selectedDateTime) {
        queryOptions.variables.params.appt_datetime = selectedDateTime
      }

      console.log(queryOptions)
      loadAppointments(queryOptions)
    }


  return (
    <div className={styles.container}>
      <Head>
        <title>Hospital Appointment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       <Container sx={{ flexGrow: 1 }}>
          <Grid container spacing={2}>
            <Grid item xs={4}>
                <Stack
                  direction={"column"}
                >
                  <Typography
                    gutterBottom={true}
                    align="center"
                    variant="h5"
                  >
                    <strong>Appointment System</strong>
                  </Typography>
                  <DateCombo
                    date={selectedDateTime}
                    setDate={setSelectedDateTime}
                  />
                  <PatientCombo 
                    data={patientData} 
                    selected={selectedPatientName}
                    setPatient={setSelectedPatientName}
                    query={setSelectedPatientQuery}
                    />
                  <DoctorCombo 
                    data={doctorData} 
                    selected={selectedDoctorName}
                    setDoctor={setSelectedDoctorName}
                    query={setSelectedDoctorQuery}
                    />
                  <Button 
                    variant="contained"
                    onClick={handleVarChange}
                  >
                    Search
                  </Button>
                  <UploadFile />
                </Stack>
            </Grid>
            <Grid item xs={8}>
              { called && apptLoading ? "Loading" : <ApptTable data={apptData}/>}
            </Grid>
        </Grid>
       </Container>
       <MakeAppt />
      </main>        
    </div>
  )
}

export const getStaticProps = async ({ params}) => {

  console.log(`Building: ${params}`)
  const client = initializeApollo()
  const { data: doctorData } = await client.query({
    query: gql`query getDoctors {
      doctor {
        doctor_id
        doctor_name
      }
    }`
  })

  const { data: patientData } = await client.query({
    query: gql`query getPatients {
      patient {
        patient_id
        patient_name
        patient_age
        patient_gender
      }
    }`
  })


  return {
    props: {
      initialApolloState: client.cache.extract(),
      patientData,
      doctorData
    },
    revalidate: 1,
  }
}

export default Home